
version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "4200:4200"
    depends_on:
      - api
  api:
    build: 
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "3000:3000"